### ISSUE TITLE
Documentation: Summary of how to set up and deploy

### ISSUE THREAD

**Issue by LawrenceLoz** [LawrenceLoz/FormulaShare-DX#23]
FormulaShare is distributed as a managed package so some areas include references to a namespace (sdfs)

To build from the source code of FormulaShare requires either:
1. Using scratch orgs with the namespace declared in in sfdx-project.json, and keeping these references in the source
2. Working with other Salesforce environments (or scatch orgs without a namespace in sfdx-project.json) and updating source to remove references to sdfs

There are also buildScratchOrg.bat and buildTestOrg.bat scripts in the source root for creating an environment and test data which should be documented.

The readme should be updated to describe how to set up an environment under each of the approaches above, and explain the steps of the batch scripts

**Comment by LawrenceLoz** [comment]
@sfdcschwabe and @thegee let me know if there's anything specific you think it's useful to cover as part of environment setup?

**Comment by sfdcschwabe** [comment]
I didn't use any of the above mentioned approaches. I've just pushed the whole repository with Visual Studio Code to a Developer Edition and execute example data or permission set assignment on my own. I agree such a script makes it more handy to setup everything up and don't miss something. I can test the scripts and try to rewrite it for mac systems after I've finished the tests for lwc.

The first step to describe is what is the variable %orgname% about? Is it necessary to change them?
I didn't work with such script in the past, but *.bat-files are for windows machines, right? Is there also a way to convert it so shell scripts which also run on a mac system?

**Comment by LawrenceLoz** [comment]
Thanks Christian, good to hear this was relatively straightforward working directly with a developer edition. The areas which are a bit fiddly are probably OK for that workflow - the sdfs namespace is currently included in sfdx-project.json but I guess it makes sense this isn't used if you're not working with scratch orgs.

The %orgname% stuff in the script is to create a helpful name for the scratch org created in the script - the commands get the current date and time, extract the month and day portions and concatenate these with "FS", which creates a name like "21DecFS". I don't have any experience with shell scripts on mac but if you'd like to have a go at doing something similar it would be nice to include that in the repo as well. The name is a nice to have really - just having a script which provisions a scratch org with the default name and automates the steps of assigning permissions and creating test data makes this workflow nicer

**Comment by sfdcschwabe** [comment]
Got it.
I am on the way to rewrite the script to make it possible to use it as a shell script. It's another 'first-try' for me to do this. :)

But currently I'm struggling with setting up an environment with dev hub and scratch org. For this I use our production org to create a scratch org and activate dev hub. Until this point everything is point and click and works fine.

My script currently very small, but looks the following:
`#!/bin/bash

#@echo off
#setlocal EnableDelayedExpansion

month=$(date +%m)
nameOfMonth=$(date +%b)
day=$(date +%d)

orgName="${day}${nameOfMonth}FS"
echo "Username for default org: ${orgName}"

sfdx force:org:create -f config/project-scratch-def.json -a ${orgName} --setdefaultusername
`
It generate the output: Username for default org: 21DezFS (like you said)

But then the first error appears:
ERROR running force:org:create:  We don’t recognize this namespace: sdfs. Did you register it in your Dev Hub org?

sfds is named as namespace in sfdx-project.json

I've found this article about [Link a Namespace to a Dev Hub Org](https://help.salesforce.com/articleView?id=sfdx_dev_reg_namespace.htm&type=5). Is there anything dangerous about this process to register a sfds namespace regarding the production org?

I've only theoretical knowledge about scratch orgs and dev hub. Sorry.

**Comment by sfdcschwabe** [comment]
For a test I've disabled the namespace parameter in sfdx-project.json.

Now the output looks like the following:

Username for default org: 21DezFS
WARNING: Warning: If you're using Contacts to Multiple Accounts, beginning with the Spring ’21 release, the feature isn't automatically enabled. You must manually enable the setting for new scratch orgs. Enable the setting in one of these ways: update the Account Settings page in Setup, add the enableRelateContactsToMultipleAccounts setting to your scratch org definition file, or enable it via Metadata API.
ERROR running force:org:create:  Unexpected token / in JSON at position 630
Created org with default username 21DezFS
ERROR running force:source:push:  Unexpected token / in JSON at position 630
Pushed source
=== Failures
USERNAME                        ERROR MESSAGE
──────────────────────────────  ─────────────────────────────────────────────────────────────────────────────────────────────
christian.schwabe@xxx.com  Permission set "FormulaShare_Admin_User" not found in target org. Do you need to push source?
=== Failures
USERNAME                        ERROR MESSAGE
──────────────────────────────  ─────────────────────────────────────────────────────────────────────────────────────────────────────────
christian.schwabe@xxx.com  Permission set "FormulaShare_Sample_App_Permissions" not found in target org. Do you need to push source?
Assigned permissions
Compiled successfully.
Executed successfully.


Set up user for debug mode
Error: Line: 2, Column: 1
Error: Variable does not exist: FSSampleAppDataGenerationService

Created test data
ERROR running force:user:create:  The scratch org does not belong to the dev hub username christian.schwabe@xxx.com. 

Try this: 
Specify the dev hub username that the scratch org belongs to with --targetdevhubusername or set a default run "sfdx force:config:set defaultdevhubusername=<username>".
Created test user fstest

**Comment by LawrenceLoz** [comment]
Great you've been able to get the org name setup in the shell script!

The first error you're seeing is one of the tricky elements of working with the namespace - the simplest way to do this is for me to authorise your dev hub org by logging into the packaging org from your dev org and approving (basically step 4 here https://help.salesforce.com/articleView?id=sfdx_dev_reg_namespace.htm&type=5). Are you comfortable to set up a temporary admin user for me to do this? I'll send you my email on linkedin.

Alternatively it should be possible to just remove the namespace attribute from the JSON and create a scratch org without the namespace. I wonder if the error you're getting is because the JSON isn't quite formatted correctly?

**Comment by sfdcschwabe** [comment]
This was not a challenge to get the composition for the orgname. :)
Did I get it right? I should grant you access to my developer edition org? I think the best is to do it with the namespace. Let's try this first.

**Comment by LawrenceLoz** [comment]
Oh something else to mention (just writing full instructions now) - you'll need to (I think) add an "sdfs__" prefix to the Sharing_Reason__c field tag value in the custom metadata record for each rule in the sample app.

So:

```
    <values>
        <field>Sharing_Reason__c</field>
        <value xsi:type="xsd:string">External_roles__c</value>
    </values>

```
Becomes:

```
    <values>
        <field>Sharing_Reason__c</field>
        <value xsi:type="xsd:string">sdfs__External_roles__c</value>
    </values>
```

Does that enable you to deploy everything to a scratch org without errors?

**Comment by sfdcschwabe** [comment]
No we get closer to finish this issue for bash script.
christianschwabe@Christians-MBP FormulaShare-DX % ./buildScratchOrg.sh                                           
Username for default org: 21DezFS
WARNING: Warning: If you're using Contacts to Multiple Accounts, beginning with the Spring ’21 release, the feature isn't automatically enabled. You must manually enable the setting for new scratch orgs. Enable the setting in one of these ways: update the Account Settings page in Setup, add the enableRelateContactsToMultipleAccounts setting to your scratch org definition file, or enable it via Metadata API.
Successfully created scratch org: 00D3N00000019FDUAY, username: test-6youa318ilee@example.com
Created org with default username 21DezFS
Job ID | 0Af3N00000kdzY5SAI
SOURCE PROGRESS | ███████████████████████████████████████░ | 318/326 Components
TYPE   PROJECT PATH                                                                                        PROBLEM
─────  ──────────────────────────────────────────────────────────────────────────────────────────────────  ───────────────────────────────────────────────────────────────────────────────────────────────
Error  fs-core/main/default/flexipages/FormulaShare_Batch_Log_Record_Page1.flexipage-meta.xml              Property 'componentInstances' not valid in version 50.0 (3:23)
Error  fs-core/main/default/flexipages/FormulaShare_Dashboard.flexipage-meta.xml                           Property 'componentInstances' not valid in version 50.0 (3:23)
Error  fs-core/main/default/flexipages/FormulaShare_Record_Logs_Record_Page.flexipage-meta.xml             Property 'componentInstances' not valid in version 50.0 (3:23)
Error  fs-core/main/default/tabs/FormulaShare_Dashboard.tab-meta.xml                                       In field: flexiPage - no FlexiPage named FormulaShare_Dashboard found
Error  fs-core/main/default/applications/FormulaShare.app-meta.xml                                         In field: tab - no CustomTab named FormulaShare_Dashboard found
Error  fs-core/main/default/permissionsets/FormulaShare_Admin_User.permissionset-meta.xml                  In field: tab - no CustomTab named FormulaShare_Dashboard found
Error  fs-core/main/default/objects/FormulaShare_Log__c/FormulaShare_Log__c.object-meta.xml                FormulaShare_Batch_Log_Record_Page1 does not exist or is not a valid override for action View.
Error  fs-core/main/default/objects/FormulaShare_Record_Log__c/FormulaShare_Record_Log__c.object-meta.xml  FormulaShare_Record_Logs_Record_Page does not exist or is not a valid override for action View.
ERROR running force:source:push:  Push failed. 

Try this: 
Check the order of your dependencies and ensure all metadata is included.
Pushed source
=== Failures
USERNAME                       ERROR MESSAGE
─────────────────────────────  ─────────────────────────────────────────────────────────────────────────────────────────────
test-6youa318ilee@example.com  Permission set "FormulaShare_Admin_User" not found in target org. Do you need to push source?
=== Failures
USERNAME                       ERROR MESSAGE
─────────────────────────────  ─────────────────────────────────────────────────────────────────────────────────────────────────────────
test-6youa318ilee@example.com  Permission set "FormulaShare_Sample_App_Permissions" not found in target org. Do you need to push source?
Assigned permissions
Compiled successfully.
Executed successfully.


Set up user for debug mode
Error: Line: 2, Column: 1
Error: Variable does not exist: FSSampleAppDataGenerationService

Created test data
=== Partial Success
Successfully created user "formulasharetestuser%orgName%@sfdx.org" with ID [0053N000003wKT8QAM] for org 00D3N00000019FDUAY.
You can see more details about this user by running "sfdx force:user:display -u formulasharetestuser%orgName%@sfdx.org".

=== Failures
ACTION                     ERROR MESSAGE
─────────────────────────  ─────────────────────────────────────────────────────────────────────────────────────────────────────────
Permission Set Assignment  Permission set "FormulaShare_Sample_App_Permissions" not found in target org. Do you need to push source?
Created test user fstest

See above some error are not fixed. I'm not quite sure if i need to remove the prefix or leave as it is but what else is to do?

There was a problem with the name of the assigned profile name for the scratch org user, because the org was created in german language. So I've added the language parameter to config/project-scratch-def.json and set it to "en_US".

By the way: I've created a new branch with these kind of modifications:

**Comment by sfdcschwabe** [comment]
https://github.com/sfdcschwabe/FormulaShare-DX/tree/%23020_setup_org

**Comment by sfdcschwabe** [comment]
The issue with the error 'Property 'componentInstances' not valid in version 50.0' is fixed to set "sourceApiVersion" to "48.0" instead of "50.0".

The following errors came up:
The username "formulasharetestuser%orgName%@sfdx.org" already exists in this or another Salesforce org. Usernames must be unique across all Salesforce orgs.

Perhaps the username error came up because the previous scratch org is still in queue to be deleted.

Some other errors came up:

14:42:24.992 (5216767683)|EXCEPTION_THROWN|[3]|System.DmlException: Insert failed. First exception on row 0; first error: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, Row Cause: bad value for restricted picklist field: Thematic_Area_Coordination_Group__c: [RowCause]
14:42:24.992 (5217852935)|FATAL_ERROR|System.DmlException: Insert failed. First exception on row 0; first error: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, Row Cause: bad value for restricted picklist field: Thematic_Area_Coordination_Group__c: [RowCause]

Trigger.sdfs.DonationTrigger: line 3, column 1
14:42:24.992 (5217895159)|FATAL_ERROR|System.DmlException: Insert failed. First exception on row 0; first error: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, Row Cause: bad value for restricted picklist field: Thematic_Area_Coordination_Group__c: [RowCause]

Trigger.sdfs.DonationTrigger: line 3, column 1

**Comment by LawrenceLoz** [comment]
Looks like there's a few complications here:

- The duplicate test user thing might be because I have this registered in my org. I hadn't really though about this... tbh I don't use this user very much and it's easy to create manually so we could just remove this line from the script
- The INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST errors should be fixed with the namespace thing I mentioned in my comment above - if you change Thematic_Area_Coordination_Group__c to sdfs__Thematic_Area_Coordination_Group__c (and similar for the Sharing_Reason__c fields of the other FormulaShare_Rule metadata records) then this should go away
- The flexipage issues and the errors relating to dependant components come up because there's a tag in the flexipage metadata which was deprecated in metadata API v49.0. I recently upgraded components in the branch I'm working in to work with API v50 and probably the simplest thing to do is to replace the versions in your branch with these and then deploy - the source is here: https://github.com/LawrenceLoz/FormulaShare-DX/tree/RelatedObjectExtension-8/fs-core/main/default/flexipages

Hopefully this is enough to get this sorted but let me know if you're still having trouble

**Comment by sfdcschwabe** [comment]
- Creation of user is removed (from both scripts)
- Is this something I also have to commit or is this just necessary for me yet?
- Of course I think this is something I have to do just for me, don't commit it and just do it on my developer edition to get the script working

To be honest: I didn't get the difference why (sometimes) you can, cannot or must use the namespace. That you have registered your namespace in my org can't be a normal state, right?

Now we've been spending most of our time on my startup difficulties, and we've lost - I think - a little bit of the focus about your issues. Sorry for that.

**Comment by sfdcschwabe** [comment]
TYPE   PROJECT PATH                                                     PROBLEM
─────  ───────────────────────────────────────────────────────────────  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error  fs-sample-app/main/default/objects/Donation__c.object-meta.xml   Cannot create a new component with the namespace: sfds.  Only components in the same namespace as the organization can be created through the API (197:21)
Error  fs-sample-app/main/default/objects/Donation__c.object-meta.xml   Cannot create a new component with the namespace: sfds.  Only components in the same namespace as the organization can be created through the API (205:21)
Error  fs-sample-app/main/default/objects/Donation__c.object-meta.xml   Cannot create a new component with the namespace: sfds.  Only components in the same namespace as the organization can be created through the API (209:21)
Error  fs-sample-app/main/default/objects/Programme__c.object-meta.xml  Cannot create a new component with the namespace: sfds.  Only components in the same namespace as the organization can be created through the API (137:21)
Error  fs-sample-app/main/default/objects/Programme__c.object-meta.xml  Cannot create a new component with the namespace: sfds.  Only components in the same namespace as the organization can be created through the API (141:21)
Error  fs-sample-app/main/default/objects/Programme__c.object-meta.xml  Cannot create a new component with the namespace: sfds.  Only components in the same namespace as the organization can be created through the API (145:21)
Error  fs-sample-app/main/default/objects/Donation__c.object-meta.xml   Cannot create a new component with the namespace: sfds.  Only components in the same namespace as the organization can be created through the API (201:21)
ERROR running force:source:push:  Push failed. 

Try this: 
Check the order of your dependencies and ensure all metadata is included.
Pushed source
=== Permsets Assigned
USERNAME                       PERMISSION SET ASSIGNMENT
─────────────────────────────  ─────────────────────────
test-qbuwf4aklscf@example.com  FormulaShare_Admin_User
=== Failures
USERNAME                       ERROR MESSAGE
─────────────────────────────  ─────────────────────────────────────────────────────────────────────────────────────────────────────────
test-qbuwf4aklscf@example.com  Permission set "FormulaShare_Sample_App_Permissions" not found in target org. Do you need to push source?

**Comment by LawrenceLoz** [comment]
Thanks for removing the user creation from both scripts and committing - this is cleaner to have in the repo like this I think.

Looks like you've sorted things for the workflow which doesn't use namespace. On reflection this is a more straightforward model and should work well for us unless you're doing anything really complex with components where namespace is important (we can revisit if this is the case at any point). The areas this can get tricky are some of the dynamic referencing in apex and some LWC event handling attributes. The authorisation is a bit of a pain - I guess for most app exchange partners this isn't something they need to do often as they'll generally work with a dev hub where various members of the team have access. With open source and individual developer orgs this doesn't work so nicely.

Looks like you've solved the deployment issues with the namespace sharing reasons. Let me know if any other probs though.

Oh and in case you're wondering why my replies are coming at odd hours - we've just relocated to Thailand so living in GMT+7 nowadays!

**Comment by sfdcschwabe** [comment]
I think it's fine and in the meantime I've created a pull request to get things together.

So far I have not wondered at what time you answer, but with the explanation now makes sense! :) 
Moving from London to Thailand under the current circumstances is an interesting decision. I don't think I would have dared to do that. Can I ask what attracts you there?

---------------
Offtopic:

I would also like to tell you about one of my ideas, which I have been thinking about for a long time, to publish it in the AppExchange. Unfortunately I don't have my project as sorted as you do and I don't have any experience with publishing in the AppExchange yet, but it's already functional and I've been using it myself for over two years. It basically revolves around managing and executing Sepa transactions in Salesforce. The application is based on the PSD2 licensed provider finAPI (https://www.finapi.io/en/developer/). So I am able to retrieve and categorize my account transactions in Salesforce. In addition, I can also perform individual transfers, sort of a white label solution for business customers to monitor their incoming payments. It is explicitly not an invoicing tool. Previous discussions with Salesforce partners unfortunately did not generate the required interest.

Translated with www.DeepL.com/Translator (free version)

**Comment by LawrenceLoz** [comment]
Thanks for the PR - this merged now.

Your idea sounds interesting. It's not an area I know a lot about but SEPA integration is something a lot of Salesforce customers will be doing in one way or another. If you haven't already it would be worth reviewing what you're doing against payments managed package providers like Chargent, Blackthorn etc - if your approach offers something over what they're doing it might be worth reaching out directly to see whether they're interested to work with you.

In terms of general considerations for publishing on the AppExchange if you'd like to chat about things to think about feel free to drop me a mail on my personal email (the one I sent on LinkedIn). There are some aspects to consider from a technical perspective and happy to run through what I've found in terms of general publishing model which might be interesting.

**Comment by LawrenceLoz** [comment]
Oh and my wife is Thai which is why we've moved here - thought we'd try out this side of the world for a few months before deciding where to be longer term!

**Comment by LawrenceLoz** [comment]
Closing the issue now that the request is merged

**Comment by sfdcschwabe** [comment]
Thank you for your interest and your offer to rely on your knowledge. Currently I have no master plan how to proceed here. I use it only for myself privately, but the dream would be of course to make it available to others. So far I have not found anyone who might want to work with me on it.

**Comment by LawrenceLoz** [comment]
Probably the first decision is whether you want to look to make it available commercially or make it open source. If you're decided on open source I'd suggest just getting a repo set up and getting started with something - gives you a way to share what you're doing with others as it's progressing. With FormulaShare I found some of the most interesting aspects coming up with a design which is truly agnostic of the org its used in and I guess that's likely to be one of the areas where you might need to adapt things to get a good foundation set up
